name: Validate project

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  norm:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci-skip]')"

    steps:
      - uses: actions/checkout@v4

      - name: Pass norminette
        run: make norm
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci-skip]')"

    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install readline
        run: sudo apt-get install libreadline-dev

      - name: Build project
        run: make

      - name: Pass tests
        run: make testonly
