name: Validate project

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  norm:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci-skip]')"

    steps:
      - uses: actions/checkout@v4

      - name: Install python3
        run: sudo apt install -y python3

      - name: Install pip
        run: sudo apt install -y python3-pip

      - name: Install norminette
        run: sudo pip3 install norminette --break-system-packages

      - name: Pass norminette
        run: sudo make norm
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci-skip]')"

    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v4

      - name: Install make
        run: sudo apt install -y make

      - name: Install readline library
        run: sudo apt install -y libreadline-dev

      - name: Install readline
        run: sudo apt install -y make

      - name: Install valgrind
        run: apt install -y valgrind

      - name: Install lcov
        run: apt install -y lcov

      - name: Pass tests
        run: sudo make testonly

      - name: Upload coverage to Codacy
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
        run: |
          sudo make covonly
          bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r ./test/coverage/coverage.info
