name: Validate project

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  norm:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci-skip]')"

    container:
      image: ghcr.io/xdec0de/42ghcr:latest

    steps:
      - uses: actions/checkout@v4

      - name: Pass norminette
        run: make norm

  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci-skip]')"

    container:
      image: ghcr.io/xdec0de/42ghcr:latest

    steps:
      - uses: actions/checkout@v4

      - name: Run tests
        run: make testonly

      - name: Upload coverage to Codacy
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
        run: |
          make covonly
          bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r ./test/coverage/coverage.info
