name: Validate project

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  norm:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci-skip]')"

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies with setup
        run: sudo ./setup.sh -y -optional

      - name: Pass norminette
        run: make norm
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci-skip]')"

    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v4

      - name: Install dependencies with setup
        run: sudo ./setup.sh -y -optional

      - name: Build project
        run: make

      - name: Pass tests
        run: make testonly

      - name: Upload coverage to Codacy
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
        run: |
          make covonly
          ls -l test/coverage/coverage.info
          bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r ./test/coverage/coverage.info
