name: Minishell validation

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci-skip]')"

    steps:
      - uses: actions/checkout@v4

      - name: Install readline
        run: sudo apt-get install libreadline-dev

      - name: Make project
        run: make

      - name: Pass norminette
        uses: alexandregv/norminette-action@v3
